spring:
  datasource:
    drive-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/rs-parking-node?useUnicode=true&amp;characterEncoding=UTF-8&amp;autoReconnect=true&amp;autoReconnectForPools=true
    username: root
    password: 1234
  jooq:
    sql-dialect: mariadb

server:
  prot: 8082
